services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    image: mariadb 
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress 
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        ADMIN: ${ADMIN}
        ADMIN_PASS: ${ADMIN_PASS}
        USER2: ${USER2}
        USER2_PASS: ${USER2_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: wordpress
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ADMIN=${ADMIN}
      - ADMIN_PASS=${ADMIN_PASS}
      - USER2=${USER2}
      - USER2_PASS=${USER2_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vcedraz-/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vcedraz-/data/mariadb

networks:
    inception:
        driver: bridge
