version: '3'

services:
nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - type: bind
        source: ./requirements/nginx/conf
        target: /etc/nginx/http.d/
      - type: bind
        source: ./requirements/nginx/tools
        target: /etc/nginx/ssl/
      - type: bind
        source: /home/${USER}/data/wordpress
        target: /var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    networks:
      - inception
    restart: always
    volumes:
      - type: bind
      - source: ${VOLPATH}mariadb
      - target: /var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: wordpress
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - type: bind
      - source: ${VOLPATH}wordpress
      - target: /var/www/

networks:
    inception:
        driver: bridge
